### ISSUE TITLE
Dockerfile should support dynamic ETL branch name

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/etl2#14]
When we build containers with dockerup.sh + Dockerfile, seems we're running a version of Docker old enough so it doesn't support the `docker build --build-arg branch=devel` param which would let us choose the branch to deploy, and so let us build containers with the correct code branch.

Currently hardcoded: may need to upgrade Docker version to make this happen. Debian default repo is too old, need to use official Docker repo.

**Comment by kxyne** [comment]
Not currently needed as we're using AMIs instead of Docker.
